name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 3: Navigate to the app directory and install dependencies
      - name: Install dependencies
        run: |
          cd frontend
          npm install

      # Step 4: Build the Next.js app
      - name: Build Next.js app
        run: |
          cd frontend
          npm run build

      # Step 5: Deploy to the server
      - name: Deploy to Server
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts

          # Copy the built files to the remote server
          rsync -avz --delete-after ./frontend/.next/ $SSH_USER@$SSH_HOST:/root/lyricscope
          rsync -avz ./frontend/public/ $SSH_USER@$SSH_HOST:/root/lyricscope

          # Ensure package.json and .next files are copied
          rsync -avz ./frontend/package.json $SSH_USER@$SSH_HOST:/root/lyricscope

          # Restart the application (using PM2, Docker, or a custom process manager)
          ssh $SSH_USER@$SSH_HOST "cd /root/lyricscope && npm install --production && pm2 restart app"
